<predicates>
calibrated-camera0-rover0,at-rover0-waypoint9,communicated_rock_data-waypoint7,have_image-rover0-objective0-colour,at-rover0-waypoint7,at-rover0-waypoint6,have_rock_analysis-rover0-waypoint2,at-rover0-waypoint5,communicated_rock_data-waypoint2,at-rover0-waypoint4,at-rover0-waypoint3,at-rover0-waypoint2,at-rover0-waypoint1,have_image-rover0-objective3-colour,have_image-rover0-objective4-colour,have_image-rover0-objective5-colour,have_image-rover0-objective1-colour,have_image-rover0-objective7-colour,empty-rover1store,communicated_soil_data-waypoint6,communicated_soil_data-waypoint9,have_image-rover0-objective6-colour,communicated_soil_data-waypoint3,have_soil_analysis-rover1-waypoint1,communicated_soil_data-waypoint4,have_soil_analysis-rover1-waypoint3,have_soil_analysis-rover1-waypoint4,have_soil_analysis-rover1-waypoint6,have_soil_analysis-rover1-waypoint9,channel_free-general,at-rover1-waypoint9,empty-rover0store,communicated_image_data-objective6-colour,have_image-rover0-objective9-colour,communicated_image_data-objective4-colour,at-rover1-waypoint5,have_rock_analysis-rover0-waypoint7,at-rover1-waypoint6,full-rover0store,at-rover1-waypoint7,have_rock_analysis-rover0-waypoint9,store_of-rover0store-rover0,at-rover1-waypoint1,at_rock_sample-waypoint2,at-rover1-waypoint2,store_of-rover1store-rover1,at-rover1-waypoint3,at-rover1-waypoint4,communicated_rock_data-waypoint9,at_rock_sample-waypoint7,available-rover1,available-rover0,have_soil_analysis-rover0-waypoint9,at_rock_sample-waypoint9,at_soil_sample-waypoint9,have_soil_analysis-rover0-waypoint4,have_soil_analysis-rover0-waypoint6,have_soil_analysis-rover0-waypoint1,at_soil_sample-waypoint3,have_soil_analysis-rover0-waypoint3,at_soil_sample-waypoint1,calibrated-camera0-rover0-waypoint1,at_soil_sample-waypoint6,communicated_image_data-objective1-colour,communicated_image_data-objective0-colour,at_soil_sample-waypoint4,communicated_image_data-objective3-colour,full-rover1store,communicated_soil_data-waypoint1,communicated_image_data-objective9-colour,communicated_image_data-objective5-colour,communicated_image_data-objective7-colour,calibrated-camera0-rover0-waypoint6,calibrated-camera0-rover0-waypoint7,calibrated-camera0-rover0-waypoint2,calibrated-camera0-rover0-waypoint3,calibrated-camera0-rover0-waypoint4,calibrated-camera0-rover0-waypoint5,
<\predicates>
<constraints>
at-rover0-waypoint9,at-rover0-waypoint7,at-rover0-waypoint6,at-rover0-waypoint5,at-rover0-waypoint4,at-rover0-waypoint3,at-rover0-waypoint2,at-rover0-waypoint1,empty-rover1store,at-rover1-waypoint9,empty-rover0store,at-rover1-waypoint5,at-rover1-waypoint6,full-rover0store,at-rover1-waypoint7,at-rover1-waypoint1,at-rover1-waypoint2,at-rover1-waypoint3,at-rover1-waypoint4,full-rover1store,
<\constraints>
<initial>
at-rover0-waypoint6,~full-rover1store,~at-rover1-waypoint7,~at-rover1-waypoint9,empty-rover1store,~calibrated-camera0-rover0-waypoint2,~at-rover1-waypoint4,~calibrated-camera0-rover0-waypoint3,~at-rover1-waypoint5,~at-rover1-waypoint6,~calibrated-camera0-rover0-waypoint1,~calibrated-camera0-rover0-waypoint6,~calibrated-camera0-rover0-waypoint7,~at-rover1-waypoint1,~calibrated-camera0-rover0-waypoint4,~at-rover1-waypoint2,~calibrated-camera0-rover0-waypoint5,~have_image-rover0-objective1-colour,channel_free-general,empty-rover0store,~have_image-rover0-objective5-colour,~full-rover0store,~have_image-rover0-objective7-colour,~have_image-rover0-objective3-colour,~have_image-rover0-objective9-colour,~communicated_soil_data-waypoint1,~communicated_soil_data-waypoint3,store_of-rover0store-rover0,at_rock_sample-waypoint2,store_of-rover1store-rover1,~have_soil_analysis-rover1-waypoint9,~communicated_image_data-objective6-colour,~communicated_image_data-objective4-colour,at-rover1-waypoint3,~communicated_image_data-objective0-colour,at_rock_sample-waypoint7,available-rover1,~communicated_soil_data-waypoint9,available-rover0,at_rock_sample-waypoint9,~have_soil_analysis-rover1-waypoint6,at_soil_sample-waypoint9,~communicated_soil_data-waypoint4,~have_soil_analysis-rover1-waypoint3,~have_soil_analysis-rover1-waypoint4,~communicated_soil_data-waypoint6,~have_soil_analysis-rover1-waypoint1,at_soil_sample-waypoint3,at_soil_sample-waypoint1,at_soil_sample-waypoint6,~calibrated-camera0-rover0,at_soil_sample-waypoint4,~communicated_rock_data-waypoint7,~have_rock_analysis-rover0-waypoint9,~communicated_rock_data-waypoint9,~communicated_rock_data-waypoint2,~have_rock_analysis-rover0-waypoint7,~have_soil_analysis-rover0-waypoint4,~have_soil_analysis-rover0-waypoint3,~have_soil_analysis-rover0-waypoint9,~at-rover0-waypoint9,~have_soil_analysis-rover0-waypoint6,~have_rock_analysis-rover0-waypoint2,~have_image-rover0-objective6-colour,~have_image-rover0-objective0-colour,~have_image-rover0-objective4-colour,~have_soil_analysis-rover0-waypoint1,~at-rover0-waypoint7,~communicated_image_data-objective7-colour,~at-rover0-waypoint5,~at-rover0-waypoint4,~at-rover0-waypoint3,~communicated_image_data-objective9-colour,~communicated_image_data-objective5-colour,~at-rover0-waypoint2,~at-rover0-waypoint1,~communicated_image_data-objective1-colour,~communicated_image_data-objective3-colour,
<\initial>
<goal>
communicated_rock_data-waypoint7,communicated_soil_data-waypoint9,communicated_rock_data-waypoint2,communicated_soil_data-waypoint4,communicated_image_data-objective4-colour,communicated_image_data-objective7-colour,
<\goal>
<preferences>
always-at_rock_sample-waypoint9
<\preferences>
<actionsSet>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint1<\name>
<pre>at-rover0-waypoint1<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint2<\name>
<pre>at-rover0-waypoint2<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint3<\name>
<pre>at-rover0-waypoint3<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint4<\name>
<pre>at-rover0-waypoint4<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint5<\name>
<pre>at-rover0-waypoint5<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint6<\name>
<pre>at-rover0-waypoint6<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>calibrate-rover0-camera0-objective6-waypoint7<\name>
<pre>at-rover0-waypoint7<\pre>
<pos>calibrated-camera0-rover0<\pos>
<\action>
<action>
<name>sample_soil-rover0-rover0store-waypoint9<\name>
<pre>at-rover0-waypoint9,at_soil_sample-waypoint9,empty-rover0store<\pre>
<pos>~at_soil_sample-waypoint9,full-rover0store,have_soil_analysis-rover0-waypoint9,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_soil-rover0-rover0store-waypoint6<\name>
<pre>at-rover0-waypoint6,at_soil_sample-waypoint6,empty-rover0store<\pre>
<pos>~at_soil_sample-waypoint6,full-rover0store,have_soil_analysis-rover0-waypoint6,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_soil-rover0-rover0store-waypoint4<\name>
<pre>at-rover0-waypoint4,at_soil_sample-waypoint4,empty-rover0store<\pre>
<pos>~at_soil_sample-waypoint4,full-rover0store,have_soil_analysis-rover0-waypoint4,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_soil-rover0-rover0store-waypoint3<\name>
<pre>at-rover0-waypoint3,at_soil_sample-waypoint3,empty-rover0store<\pre>
<pos>~at_soil_sample-waypoint3,full-rover0store,have_soil_analysis-rover0-waypoint3,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_soil-rover0-rover0store-waypoint1<\name>
<pre>at-rover0-waypoint1,at_soil_sample-waypoint1,empty-rover0store<\pre>
<pos>~at_soil_sample-waypoint1,full-rover0store,have_soil_analysis-rover0-waypoint1,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_soil-rover1-rover1store-waypoint9<\name>
<pre>at-rover1-waypoint9,at_soil_sample-waypoint9,empty-rover1store<\pre>
<pos>~at_soil_sample-waypoint9,full-rover1store,have_soil_analysis-rover1-waypoint9,~empty-rover1store<\pos>
<\action>
<action>
<name>sample_soil-rover1-rover1store-waypoint6<\name>
<pre>at-rover1-waypoint6,at_soil_sample-waypoint6,empty-rover1store<\pre>
<pos>~at_soil_sample-waypoint6,full-rover1store,have_soil_analysis-rover1-waypoint6,~empty-rover1store<\pos>
<\action>
<action>
<name>sample_soil-rover1-rover1store-waypoint4<\name>
<pre>at-rover1-waypoint4,at_soil_sample-waypoint4,empty-rover1store<\pre>
<pos>~at_soil_sample-waypoint4,full-rover1store,have_soil_analysis-rover1-waypoint4,~empty-rover1store<\pos>
<\action>
<action>
<name>sample_soil-rover1-rover1store-waypoint3<\name>
<pre>at-rover1-waypoint3,at_soil_sample-waypoint3,empty-rover1store<\pre>
<pos>~at_soil_sample-waypoint3,full-rover1store,have_soil_analysis-rover1-waypoint3,~empty-rover1store<\pos>
<\action>
<action>
<name>sample_soil-rover1-rover1store-waypoint1<\name>
<pre>at-rover1-waypoint1,at_soil_sample-waypoint1,empty-rover1store<\pre>
<pos>~at_soil_sample-waypoint1,full-rover1store,have_soil_analysis-rover1-waypoint1,~empty-rover1store<\pos>
<\action>
<action>
<name>sample_rock-rover0-rover0store-waypoint9<\name>
<pre>at-rover0-waypoint9,at_rock_sample-waypoint9,empty-rover0store<\pre>
<pos>have_rock_analysis-rover0-waypoint9,~at_rock_sample-waypoint9,full-rover0store,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_rock-rover0-rover0store-waypoint7<\name>
<pre>at-rover0-waypoint7,at_rock_sample-waypoint7,empty-rover0store<\pre>
<pos>have_rock_analysis-rover0-waypoint7,~at_rock_sample-waypoint7,full-rover0store,~empty-rover0store<\pos>
<\action>
<action>
<name>sample_rock-rover0-rover0store-waypoint2<\name>
<pre>at-rover0-waypoint2,at_rock_sample-waypoint2,empty-rover0store<\pre>
<pos>have_rock_analysis-rover0-waypoint2,~at_rock_sample-waypoint2,full-rover0store,~empty-rover0store<\pos>
<\action>
<action>
<name>navigate-waypoint1-waypoint6-waypoint5<\name>
<pre>at-rover0-waypoint1,available-rover0<\pre>
<pos>~at-rover0-waypoint1,at-rover0-waypoint6:~at-rover0-waypoint1,at-rover0-waypoint5<\pos>
<\action>
<action>
<name>navigate-waypoint2-waypoint6-waypoint2<\name>
<pre>at-rover0-waypoint2,available-rover0<\pre>
<pos>~at-rover0-waypoint2,at-rover0-waypoint6:at-rover0-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,available-rover0<\pre>
<pos>~at-rover0-waypoint2,at-rover0-waypoint7<\pos>
<\action>
<action>
<name>navigate-waypoint2-waypoint9<\name>
<pre>at-rover0-waypoint2,available-rover0<\pre>
<pos>~at-rover0-waypoint2,at-rover0-waypoint9<\pos>
<\action>
<action>
<name>navigate-waypoint3-waypoint6<\name>
<pre>at-rover0-waypoint3,available-rover0<\pre>
<pos>~at-rover0-waypoint3,at-rover0-waypoint6<\pos>
<\action>
<action>
<name>navigate-waypoint4-waypoint1<\name>
<pre>at-rover0-waypoint4,available-rover0<\pre>
<pos>~at-rover0-waypoint4,at-rover0-waypoint1<\pos>
<\action>
<action>
<name>navigate-waypoint4-waypoint2<\name>
<pre>at-rover0-waypoint4,available-rover0<\pre>
<pos>~at-rover0-waypoint4,at-rover0-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,available-rover0<\pre>
<pos>~at-rover0-waypoint4,at-rover0-waypoint7<\pos>
<\action>
<action>
<name>navigate-waypoint6-waypoint3<\name>
<pre>at-rover0-waypoint6,available-rover0<\pre>
<pos>~at-rover0-waypoint6,at-rover0-waypoint3<\pos>
<\action>
<action>
<name>navigate-waypoint7-waypoint2<\name>
<pre>at-rover0-waypoint7,available-rover0<\pre>
<pos>~at-rover0-waypoint7,at-rover0-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint7-waypoint4<\name>
<pre>at-rover0-waypoint7,available-rover0<\pre>
<pos>~at-rover0-waypoint7,at-rover0-waypoint4<\pos>
<\action>
<action>
<name>navigate-waypoint9-waypoint2<\name>
<pre>at-rover0-waypoint9,available-rover0<\pre>
<pos>~at-rover0-waypoint9,at-rover0-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint9-waypoint3-waypoint6<\name>
<pre>at-rover0-waypoint9,available-rover0<\pre>
<pos>~at-rover0-waypoint9,at-rover0-waypoint3:~at-rover0-waypoint9,at-rover0-waypoint6<\pos>
<\action>
<action>
<name>navigate-waypoint1-waypoint5<\name>
<pre>at-rover1-waypoint1,available-rover1<\pre>
<pos>~at-rover1-waypoint1,at-rover1-waypoint5<\pos>
<\action>
<action>
<name>navigate-waypoint1-waypoint6<\name>
<pre>at-rover1-waypoint1,available-rover1<\pre>
<pos>~at-rover1-waypoint1,at-rover1-waypoint6<\pos>
<\action>
<action>
<name>navigate-waypoint2-waypoint6<\name>
<pre>at-rover1-waypoint2,available-rover1<\pre>
<pos>~at-rover1-waypoint2,at-rover1-waypoint6<\pos>
<\action>
<action>
<name>navigate-waypoint2-waypoint7<\name>
<pre>at-rover1-waypoint2,available-rover1<\pre>
<pos>~at-rover1-waypoint2,at-rover1-waypoint7<\pos>
<\action>
<action>
<name>navigate-waypoint2-waypoint9<\name>
<pre>at-rover1-waypoint2,available-rover1<\pre>
<pos>~at-rover1-waypoint2,at-rover1-waypoint9<\pos>
<\action>
<action>
<name>navigate-waypoint3-waypoint6<\name>
<pre>at-rover1-waypoint3,available-rover1<\pre>
<pos>~at-rover1-waypoint3,at-rover1-waypoint6<\pos>
<\action>
<action>
<name>navigate-waypoint4-waypoint1<\name>
<pre>at-rover1-waypoint4,available-rover1<\pre>
<pos>~at-rover1-waypoint4,at-rover1-waypoint1<\pos>
<\action>
<action>
<name>navigate-waypoint4-waypoint2<\name>
<pre>at-rover1-waypoint4,available-rover1<\pre>
<pos>~at-rover1-waypoint4,at-rover1-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint4-waypoint7<\name>
<pre>at-rover1-waypoint4,available-rover1<\pre>
<pos>~at-rover1-waypoint4,at-rover1-waypoint7<\pos>
<\action>
<action>
<name>navigate-waypoint6-waypoint3<\name>
<pre>at-rover1-waypoint6,available-rover1<\pre>
<pos>~at-rover1-waypoint6,at-rover1-waypoint3<\pos>
<\action>
<action>
<name>navigate-waypoint7-waypoint2<\name>
<pre>at-rover1-waypoint7,available-rover1<\pre>
<pos>~at-rover1-waypoint7,at-rover1-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint7-waypoint4<\name>
<pre>at-rover1-waypoint7,available-rover1<\pre>
<pos>~at-rover1-waypoint7,at-rover1-waypoint4<\pos>
<\action>
<action>
<name>navigate-waypoint9-waypoint2<\name>
<pre>at-rover1-waypoint9,available-rover1<\pre>
<pos>~at-rover1-waypoint9,at-rover1-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint9-waypoint3<\name>
<pre>at-rover1-waypoint9,available-rover1<\pre>
<pos>~at-rover1-waypoint9,at-rover1-waypoint3<\pos>
<\action>
<action>
<name>navigate-waypoint9-waypoint6<\name>
<pre>at-rover1-waypoint9,available-rover1<\pre>
<pos>~at-rover1-waypoint9,at-rover1-waypoint6<\pos>
<\action>
<action>
<name>drop-rover0-rover0store<\name>
<pre>full-rover0store,store_of-rover0store-rover0<\pre>
<pos>~full-rover0store,empty-rover0store<\pos>
<\action>
<action>
<name>drop-rover1-rover1store<\name>
<pre>full-rover1store,store_of-rover1store-rover1<\pre>
<pos>~full-rover1store,empty-rover1store<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective0-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective0-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective1-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective1-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective1-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective1-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective1-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective1-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective3-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective3-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective3-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective3-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective3-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective3-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint4-objective3-camera0-colour<\name>
<pre>at-rover0-waypoint4,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective3-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint5-objective3-camera0-colour<\name>
<pre>at-rover0-waypoint5,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective3-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint6-objective3-camera0-colour<\name>
<pre>at-rover0-waypoint6,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective3-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective4-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective4-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective4-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective4-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective4-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective4-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint4-objective4-camera0-colour<\name>
<pre>at-rover0-waypoint4,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective4-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint5-objective4-camera0-colour<\name>
<pre>at-rover0-waypoint5,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective4-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint6-objective4-camera0-colour<\name>
<pre>at-rover0-waypoint6,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective4-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint4-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint4,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint5-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint5,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint6-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint6,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint7-objective5-camera0-colour<\name>
<pre>at-rover0-waypoint7,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective5-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint4-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint4,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint5-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint5,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint6-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint6,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint7-objective6-camera0-colour<\name>
<pre>at-rover0-waypoint7,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective6-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint4-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint4,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint5-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint5,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint6-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint6,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint7-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint7,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint9-objective7-camera0-colour<\name>
<pre>at-rover0-waypoint9,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective7-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint1-objective9-camera0-colour<\name>
<pre>at-rover0-waypoint1,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective9-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint2-objective9-camera0-colour<\name>
<pre>at-rover0-waypoint2,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective9-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint3-objective9-camera0-colour<\name>
<pre>at-rover0-waypoint3,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective9-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint4-objective9-camera0-colour<\name>
<pre>at-rover0-waypoint4,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective9-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint5-objective9-camera0-colour<\name>
<pre>at-rover0-waypoint5,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective9-colour<\pos>
<\action>
<action>
<name>take_image-rover0-waypoint6-objective9-camera0-colour<\name>
<pre>at-rover0-waypoint6,calibrated-camera0-rover0<\pre>
<pos>~calibrated-camera0-rover0,have_image-rover0-objective9-colour<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint2-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_rock_analysis-rover0-waypoint2<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint2,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint7-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_rock_analysis-rover0-waypoint7<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint7,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint9-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_rock_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint2-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_rock_analysis-rover0-waypoint2<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint2,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint7-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_rock_analysis-rover0-waypoint7<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint7,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint9-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_rock_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint2-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_rock_analysis-rover0-waypoint2<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint2,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint7-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_rock_analysis-rover0-waypoint7<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint7,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint9-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_rock_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint2-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_rock_analysis-rover0-waypoint2<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint2,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint7-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_rock_analysis-rover0-waypoint7<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint7,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint9-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_rock_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint2-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_rock_analysis-rover0-waypoint2<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint2,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint7-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_rock_analysis-rover0-waypoint7<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint7,available-rover0<\pos>
<\action>
<action>
<name>communicate_rock_data-rover0-general-waypoint9-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_rock_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_rock_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint1-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_soil_analysis-rover0-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint3-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_soil_analysis-rover0-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint4-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_soil_analysis-rover0-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint6-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_soil_analysis-rover0-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint9-waypoint2-waypoint7<\name>
<pre>at-rover0-waypoint2,have_soil_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint1-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_soil_analysis-rover0-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint3-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_soil_analysis-rover0-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint4-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_soil_analysis-rover0-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint6-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_soil_analysis-rover0-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint9-waypoint3-waypoint7<\name>
<pre>at-rover0-waypoint3,have_soil_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint1-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_soil_analysis-rover0-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint3-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_soil_analysis-rover0-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint4-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_soil_analysis-rover0-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint6-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_soil_analysis-rover0-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint9-waypoint4-waypoint7<\name>
<pre>at-rover0-waypoint4,have_soil_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint1-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_soil_analysis-rover0-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint3-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_soil_analysis-rover0-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint4-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_soil_analysis-rover0-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint6-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_soil_analysis-rover0-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint9-waypoint5-waypoint7<\name>
<pre>at-rover0-waypoint5,have_soil_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint1-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_soil_analysis-rover0-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint3-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_soil_analysis-rover0-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint4-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_soil_analysis-rover0-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint6-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_soil_analysis-rover0-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover0-general-waypoint9-waypoint6-waypoint7<\name>
<pre>at-rover0-waypoint6,have_soil_analysis-rover0-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover0<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint1-waypoint2-waypoint7<\name>
<pre>at-rover1-waypoint2,have_soil_analysis-rover1-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint3-waypoint2-waypoint7<\name>
<pre>at-rover1-waypoint2,have_soil_analysis-rover1-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint4-waypoint2-waypoint7<\name>
<pre>at-rover1-waypoint2,have_soil_analysis-rover1-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint6-waypoint2-waypoint7<\name>
<pre>at-rover1-waypoint2,have_soil_analysis-rover1-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint9-waypoint2-waypoint7<\name>
<pre>at-rover1-waypoint2,have_soil_analysis-rover1-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint1-waypoint3-waypoint7<\name>
<pre>at-rover1-waypoint3,have_soil_analysis-rover1-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint3-waypoint3-waypoint7<\name>
<pre>at-rover1-waypoint3,have_soil_analysis-rover1-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint4-waypoint3-waypoint7<\name>
<pre>at-rover1-waypoint3,have_soil_analysis-rover1-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint6-waypoint3-waypoint7<\name>
<pre>at-rover1-waypoint3,have_soil_analysis-rover1-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint9-waypoint3-waypoint7<\name>
<pre>at-rover1-waypoint3,have_soil_analysis-rover1-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint1-waypoint4-waypoint7<\name>
<pre>at-rover1-waypoint4,have_soil_analysis-rover1-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint3-waypoint4-waypoint7<\name>
<pre>at-rover1-waypoint4,have_soil_analysis-rover1-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint4-waypoint4-waypoint7<\name>
<pre>at-rover1-waypoint4,have_soil_analysis-rover1-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint6-waypoint4-waypoint7<\name>
<pre>at-rover1-waypoint4,have_soil_analysis-rover1-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint9-waypoint4-waypoint7<\name>
<pre>at-rover1-waypoint4,have_soil_analysis-rover1-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint1-waypoint5-waypoint7<\name>
<pre>at-rover1-waypoint5,have_soil_analysis-rover1-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint3-waypoint5-waypoint7<\name>
<pre>at-rover1-waypoint5,have_soil_analysis-rover1-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint4-waypoint5-waypoint7<\name>
<pre>at-rover1-waypoint5,have_soil_analysis-rover1-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint6-waypoint5-waypoint7<\name>
<pre>at-rover1-waypoint5,have_soil_analysis-rover1-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint9-waypoint5-waypoint7<\name>
<pre>at-rover1-waypoint5,have_soil_analysis-rover1-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint1-waypoint6-waypoint7<\name>
<pre>at-rover1-waypoint6,have_soil_analysis-rover1-waypoint1<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint1,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint3-waypoint6-waypoint7<\name>
<pre>at-rover1-waypoint6,have_soil_analysis-rover1-waypoint3<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint3,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint4-waypoint6-waypoint7<\name>
<pre>at-rover1-waypoint6,have_soil_analysis-rover1-waypoint4<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint4,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint6-waypoint6-waypoint7<\name>
<pre>at-rover1-waypoint6,have_soil_analysis-rover1-waypoint6<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint6,available-rover1<\pos>
<\action>
<action>
<name>communicate_soil_data-rover1-general-waypoint9-waypoint6-waypoint7<\name>
<pre>at-rover1-waypoint6,have_soil_analysis-rover1-waypoint9<\pre>
<pos>channel_free-general,communicated_soil_data-waypoint9,available-rover1<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective0-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective0-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective0-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective1-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective1-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective1-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective3-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective3-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective3-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective4-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective4-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective4-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective5-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective5-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective5-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective6-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective6-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective6-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective7-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective7-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective7-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective9-colour-waypoint2-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint2,available-rover0,have_image-rover0-objective9-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective9-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective0-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective0-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective0-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective1-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective1-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective1-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective3-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective3-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective3-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective4-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective4-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective4-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective5-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective5-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective5-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective6-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective6-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective6-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective7-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective7-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective7-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective9-colour-waypoint3-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint3,available-rover0,have_image-rover0-objective9-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective9-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective0-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective0-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective0-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective1-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective1-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective1-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective3-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective3-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective3-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective4-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective4-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective4-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective5-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective5-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective5-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective6-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective6-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective6-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective7-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective7-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective7-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective9-colour-waypoint4-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint4,available-rover0,have_image-rover0-objective9-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective9-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective0-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective0-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective0-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective1-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective1-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective1-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective3-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective3-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective3-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective4-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective4-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective4-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective5-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective5-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective5-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective6-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective6-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective6-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective7-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective7-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective7-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective9-colour-waypoint5-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint5,available-rover0,have_image-rover0-objective9-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective9-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective0-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective0-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective0-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective1-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective1-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective1-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective3-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective3-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective3-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective4-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective4-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective4-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective5-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective5-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective5-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective6-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective6-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective6-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective7-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective7-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective7-colour,available-rover0<\pos>
<\action>
<action>
<name>communicate_image_data-rover0-general-objective9-colour-waypoint6-waypoint7<\name>
<pre>channel_free-general,at-rover0-waypoint6,available-rover0,have_image-rover0-objective9-colour<\pre>
<pos>channel_free-general,communicated_image_data-objective9-colour,available-rover0<\pos>
<\action>
<\actionsSet>
