<predicates>
at-rover0-waypoint9,at-rover0-waypoint8,always-available-rover0
<\predicates>
<constraints>
at-rover0-waypoint9,at-rover0-waypoint8,
<\constraints>
<initial>
at-rover0-waypoint2,available-rover0
<\initial>
<goal>
at-rover0-waypoint9
<\goal>
<preferences>
always-available-rover0
<\preferences>
<actionsSet>
<action>
<name>navigate-waypoint0-waypoint2<\name>
<pre>at-rover0-waypoint0,available-rover0<\pre>
<pos>~at-rover0-waypoint0,at-rover0-waypoint2<\pos>
<\action>
<\actionsSet>
